spring.application.name=cachingApp

spring.datasource.url=jdbc:postgresql://localhost:5432/caching
spring.datasource.username=postgres
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#redis config
#spring.data.redis.host = localhost
#spring.data.redis.port = 6379


spring.data.redis.host = redis-18374.c323.us-east-1-2.ec2.cloud.redislabs.com
spring.data.redis.port = 18374
spring.data.redis.password = QSIF8zdYde55uQB9CadLmduUCW0Hq345